### ISSUE TITLE
[Documentation] create CONTRIBUTING.md

### ISSUE THREAD

**Issue by lixuna** [lfn-cnti/certification#108]
**Describe the update:**
- create CONTRIBUTING.md for /certification
- ex. https://github.com/lfn-cnti/certification/blob/main/CONTRIBUTING.md

**Describe why update is needed**
- include info and links from https://wiki.lfnetworking.org/display/LN/Certification
- include link to https://wiki.lfnetworking.org/pages/viewpage.action?pageId=113213592
- include meeting times
- include slack channels

**Related Examples**
- https://github.com/lfn-cnti/bestpractices/blob/main/CONTRIBUTING.md
- https://github.com/cnti-testcatalog/testsuite/blob/main/CONTRIBUTING.md

**Tasks**
- [ ] Draft new CONTRIBUTING.md
- [ ] submit PR
- [ ] Peer review

**Comment by Smitholi67** [comment]
Already addressed in https://github.com/lfn-cnti/certification/pull/142
