### ISSUE TITLE
Enable GitHub Discussions

### ISSUE THREAD

**Issue by cassamajor** [lfn-cnti/certification#151]
[CONTRIBUTING.md](https://github.com/lfn-cnti/cnti/tree/main/CONTRIBUTING.md) in the [CNTi](https://github.com/lfn-cnti/cnti) repository currently suggests to "Join an existing discussion or create a new one". It provides a link to the [Certification Discussion board](https://github.com/lfn-cnti/certification/discussions), however it is not currently enabled and leads to a 404 Page Not Found.

**Comment by martin-mat** [comment]
Discussions enabled
https://github.com/lfn-cnti/certification/discussions
