### ISSUE TITLE
[Branding] Determine name of LFN CNTI Certification

### ISSUE THREAD

**Issue by taylor** [lfn-cnti/certification#66]
This issue confirms that we will call the certification program "LFN CNTI Certification" for the H1 2024 release

**Comment by lixuna** [comment]
@taylor @Smitholi67 is the official name for the certification going to be "LFN CNTI Certification"?

**Comment by taylor** [comment]
At this time I recommend that as the name

**Comment by Smitholi67** [comment]
Lgtm

**Comment by lixuna** [comment]
Confirmed: the certification program is named "LFN CNTI Certification" for the H1 2024 release
