### ISSUE TITLE
[Design] Brand Guide for Certification Badge usage

### ISSUE THREAD

**Issue by lixuna** [lfn-cnti/certification#71]
**Describe the update:**
Create Brand Guide for CNTI Certification logo and badge
- similar to https://github.com/cncf/artwork/tree/master/other/certified-cnf and https://github.com/cncf/artwork/blob/main/other/certified-cnf/certified-cnf-brand-guide.pdf

**Describe why update is needed**
- CNF WG (and CNCF’s related Cloud Native Telco efforts) has moved to LFN (see [wiki](https://wiki.lfnetworking.org/display/LN/Cloud+Native+Telecom+Networking+Initiative))

**Tasks**
- [ ]  blocked by #68 
- [ ] request assistance from design team to update https://github.com/cncf/artwork/tree/master/other/certified-cnf for CNTI Certification

**Comment by lixuna** [comment]
@Smitholi67 is this something that your design team can help with after they have created the CNTi logos and CNTi Certification badge?

**Comment by Smitholi67** [comment]
6/21/2024 - Shared the attached draft of branding guideline with Jill Lovato and rest of CNTi TSC for review/feedback

[Cloud-Native-Telecom-Guidelines-R1.pdf](https://github.com/user-attachments/files/15928493/Cloud-Native-Telecom-Guidelines-R1.pdf)

**Comment by Smitholi67** [comment]
7/9/2024 - Jill Lovato reviewed and approved the CNTi Branding Guideline.

**Comment by Smitholi67** [comment]
Branding guideline is now stored at:  https://github.com/lfn-cnti/artwork/blob/main/CNTI_Branding_Guideline_Rel1.pdf
